"""
Created on Fri Feb 26 11:42:14 2016

@author: akirkland & michellegarfias
"""

def find_motif(s,t):
	result = []
	tlen = len(t)
	slen = len(s)
	for i in range(0, slen - tlen + 1):
		if s[i:i+tlen] == t:
			result.append(i+1)        

	for x in result:
		print(x)


find_motif('TCGCCTCATCTGAGCGCCTCACGCCTCACGCCTCATTCGCGCCTCAGACGCCTCATAAGCCGCCTCAACGCGCCTCACCGCCTCATACGCCTCACCCGAGACGCCTCACGCCTCACGCCTCAAGCGCCTCACGCGCCTCACGCCTCAATCGCCTCATCCGCCTCAACGCGCCTCATTCGCCTCACCGCCTCAGTCTTGCCCCGCCTCACGGGAAACTTCGCCTCACGCCTCAGTCGCCTCAACGCCTCAGCGCCTCAGCCTTCGCCTCACGCCTCACGCCTCACGCCTCACACGCCTCACGCCTCAGCGCCTCAGGCCGGCCGCCTCATGCCGCCTCAGGTGAGGCGCCGCCTCACGCCTCACGCCTCAGCCGCCTCACGCCTCATAATGCGCCTCACTTTCGCCTCACGCCTCACGGATCCGCCTCAGCGACGCCTCAAATGCGGCTATCGCCTCATTGTCGCCTCACGCACGCCTCATTCGCCTCAACTCGCCTCAACGCCTCACGTAATAGAGCGCCTCAGGCGCCTCAGCGCCGCCTCACGGACGCCTCATCGCCTCACGCCTCAGAGCCGCCTCACGCCTCACCCCTGGCGCGCCTCAATCTGACGCCGCCTCATTAGATATTCGCCTCAAGCGCCTCATACGCCTCAACGGCCCGCCTCAGAACGGCGCCTCAACGCCTCAGCGCCTCAGGACGCGCCTCAGTAGAGTGCTCCGCCTCACGCCTCAACGCCTCAACGCCTCAGGAGTTCGCCTCAACGCCTCAGCCGCCTCATATCAACTCGCCTCAGGCGCCTCATCTTAGTCACGCCTCAATCGCCTCACGCCTCAGGCGCCTCAACGCCTCAGGCGCCTCA', 'CGCCTCACG')

